app_name: cloud-file-storage

env: dev

http:
  addr: ":8080"

log:
  level: "info"
  format: "json"

db:
  dsn: 

smtp:
  host: "smtp.gmail.com"
  port: 587
  name: 
  email: 
  password: 

s3:
  endpoint: "https://s3.amazonaws.com"
  region: "us-east-1"
  bucket: 
  access_key_id: 
  secret_access_key: 
  use_path_style: false

rate_limits:
  global_rps: 200

features:
  previews: true
